// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TrackerMe
{
	public partial class PagoViewController : UITableViewController
	{
		public PagoViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
